version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    # イメージ名を指定
    image: hinamimi/atcoder-test:dev

    # localとcontainer間のファイルを同期させる
    # ${local}:{container}
    volumes:
      - ../problems:/root/problems:cached
      - ../library:/root/library:cached
      - ../acc-template-python:/root/.config/atcoder-cli-nodejs/python:cached
      - ../.vscode:/root/.vscode:cached

    # オプション これらのconfigファイルがなければコメントアウト
      - ~/.gitconfig:/root/.gitconfig
      - ~/.bashrc:/root/.bashrc
      - ~/.bash_profile:/root/.bash_profile
      - ~/.zshrc:/root/.zshrc
      - ~/.zprofile:/root/.zprofile
      - ~/.aliases:/root/.aliases

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
